version: '3.8'

services:
  users-service:
    image: yisusyaro/users-service:1
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: users-container
    ports:
      - '5000:5000'
    environment:
      - START=start_users
      - FRONTEND=http://127.0.0.1:5500
      - ENV=production
      - JWT_SECRET=nRuDMYTAZC8muFz4
      - DATABASE=${DATABASE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  characters-service:
    image: yisusyaro/characters-service:1
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: characters-container
    ports:
      - '5001:5001'
    environment:
      - START=start_characters
      - FRONTEND=http://127.0.0.1:5500
      - ENV=production
      - JWT_SECRET=nRuDMYTAZC8muFz4
      - MARVEL_PUBLIC_KEY=${MARVEL_PUBLIC_KEY}
      - MARVEL_PRIVATE_KEY=${MARVEL_PRIVATE_KEY}

  comics-service:
    image: yisusyaro/comics-service:1
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: comics-container
    ports:
      - '5002:5002'
    environment:
      - START=start_comics
      - FRONTEND=http://127.0.0.1:5500
      - ENV=production
      - JWT_SECRET=nRuDMYTAZC8muFz4
      - MARVEL_PUBLIC_KEY=${MARVEL_PUBLIC_KEY}
      - MARVEL_PRIVATE_KEY=${MARVEL_PRIVATE_KEY}
