version: '3.8'

services:
  users-service:
    build:
      context: ./users
      dockerfile: ./Dockerfile-dev
    container_name: users-container
    volumes:
      - ./users/:/usr/src/app
    ports:
      - '5000:5000'
    stdin_open: true
    environment:
      - FRONTEND=http://127.0.0.1:5500
      - ENV=test
      - DATABASE=${DATABASE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
