version: '3.8'

services:
  users-service:
    build:
      context: ./server
      dockerfile: ./Dockerfile-dev
    container_name: users-container
    volumes:
      - ./server/:/usr/src/app
    ports:
      - '5000:5000'
    stdin_open: true
    environment:
      - FRONTEND=http://127.0.0.1:5500
      - ENV=test
      - DATABASE=${DATABASE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=nRuDMYTAZC8muFz4

  characters-and-comics-service:
    build:
      context: ./server
      dockerfile: ./Dockerfile-dev
    container_name: characters-and-comics-container
    volumes:
      - ./server/:/usr/src/app
    ports:
      - '5001:5001'
    stdin_open: true
    environment:
      - FRONTEND=http://127.0.0.1:5500
      - ENV=test
      - JWT_SECRET=nRuDMYTAZC8muFz4
      - MARVEL_PUBLIC_KEY=${MARVEL_PUBLIC_KEY}
      - MARVEL_PRIVATE_KEY=${MARVEL_PRIVATE_KEY}
