version: '3.8'

services:
  users-service:
    build:
      context: ./users
      dockerfile: ./Dockerfile
    container_name: users-container
    ports:
      - '5000:5000'
    environment:
      - FRONTEND=http://127.0.0.1:5500
      - ENV=production
      - DATABASE=${DATABASE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
